### ISSUE TITLE
Some question about your thetacontroller in auto

### ISSUE THREAD

**Issue by mendax1234** [SeanSun6814/FRC0ToAutonomous#1]
Thanks for providing such a greatful video. Notice that your team can let your swerve rotate during the auto and you use the WPI's SwerveControllerCommand. My question is how does your team tune your thetacontroller ? How do you calculate your TrapezoidProfile.Constraints.Can you give our team some suggestions on how to get the suitable value for our swerve. Thanks!

**Comment by SeanSun6814** [comment]
You might need to do some trial and error for your constants. For more info on how to tune PID controllers, check out 0 to Autonomous videos #3, #4. TrapezoidProfile.Constraints are the maximum rotational speeds that you want the robot to spin at. They are in radians, so feel free to do some unit conversion to get a sense of how fast that actually is. For further help, check out the FRC Discord and ChiefDelphi.
